apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  description: ${{ values.description }}
  annotations:
    github.com/project-slug: ${{ values.destination.owner + "/" + values.destination.repo }}
    tektonci/build-namespace: ${{ values.namespace }}
    janus-idp.io/tekton: ${{ values.name }}-ci-cd
spec:
  type: service
  lifecycle: dev
  owner: ${{ values.owner }}
