apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  description: ${{ values.description }}
  annotations:
    github.com/project-slug: ${{ values.destination.owner + "/" + values.destination.repo }}
    backstage.io/kubernetes-namespace: ${{ values.namespace }}
    backstage.io/kubernetes-id: ${{ values.name }}
    backstage.io/kubernetes-label-selector: backstage.io/kubernetes-id=${{ values.name }}
    janus-idp.io/tekton: ${{ values.name }}
spec:
  type: service
  lifecycle: dev
  owner: ${{ values.owner }}
