apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: ${{ values.name }}-run-
  namespace: ${{ values.namespace }}
  labels:
    app: ${{ values.name }}
    tekton.dev/pipeline: ${{ values.name }}-ci-cd
spec:
  pipelineRef:
    name: ${{ values.name }}-ci-cd
  params:
    - name: git-url
      value: https://github.com/${{ values.destination.owner }}/${{ values.destination.repo }}.git
    - name: git-revision
      value: main
    - name: image-name
      value: image-registry.openshift-image-registry.svc:5000/${{ values.namespace }}/${{ values.name }}:latest
    - name: deploy-namespace
      value: ${{ values.namespace }}
  workspaces:
    - name: shared-workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
