apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: ${{ values.name }}-github-binding
  namespace: ${{ values.namespace }}
  labels:
    app: ${{ values.name }}
spec:
  params:
    - name: git-url
      value: $(body.repository.clone_url)
    - name: git-revision
      value: $(body.after)
---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: ${{ values.name }}-github-template
  namespace: ${{ values.namespace }}
  labels:
    app: ${{ values.name }}
spec:
  params:
    - name: git-url
    - name: git-revision
  resourcetemplates:
    - apiVersion: tekton.dev/v1
      kind: PipelineRun
      metadata:
        generateName: ${{ values.name }}-webhook-
        namespace: ${{ values.namespace }}
        labels:
          app: ${{ values.name }}
          tekton.dev/pipeline: ${{ values.name }}-ci-cd
      spec:
        pipelineRef:
          name: ${{ values.name }}-ci-cd
        params:
          - name: git-url
            value: $(tt.params.git-url)
          - name: git-revision
            value: $(tt.params.git-revision)
          - name: image-name
            value: image-registry.openshift-image-registry.svc:5000/${{ values.namespace }}/${{ values.name }}:latest
          - name: deploy-namespace
            value: ${{ values.namespace }}
        workspaces:
          - name: shared-workspace
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi
---
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: ${{ values.name }}-listener
  namespace: ${{ values.namespace }}
  labels:
    app: ${{ values.name }}
spec:
  serviceAccountName: pipeline
  triggers:
    - name: github-push
      interceptors:
        - ref:
            name: github
          params:
            - name: eventTypes
              value:
                - push
      bindings:
        - ref: ${{ values.name }}-github-binding
      template:
        ref: ${{ values.name }}-github-template
