apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${{ values.name }}
  labels:
    app: ${{ values.name }}
    app.kubernetes.io/name: python
    app.kubernetes.io/part-of: ${{ values.name }}
    app.openshift.io/runtime: python
    backstage.io/kubernetes-id: ${{ values.name }}
  annotations:
    app.openshift.io/vcs-uri: https://github.com/${{ values.destination.owner }}/${{ values.destination.repo }}
    app.openshift.io/vcs-ref: main
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${{ values.name }}
  template:
    metadata:
      labels:
        app: ${{ values.name }}
        backstage.io/kubernetes-id: ${{ values.name }}
    spec:
      containers:
        - name: mcp-server
          image: image-registry.openshift-image-registry.svc:5000/${{ values.namespace }}/${{ values.destination.repo }}:latest
          ports:
            - containerPort: ${{ values.port }}
          env:
            - name: API_BASE_URL
              value: ${{ values.apiBaseUrl }}
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: "1"
              memory: 512Mi
